### ISSUE TITLE
Add next_date sensor attribute

### ISSUE THREAD

**Issue by apivaral** [pinkywafer/Anniversaries#108]
Please add **next_date** to the sensor, and **next_date_format** to configuration, with the date of the next anniversary.

This would be very useful to be able to show the weekday, for example next birthday will be Friday, Sep 1

Thank you for your great work in this integration!

**Comment by pinkywafer** [comment]
I don't see any reason why not - the next date could be useful.
However, due to changes in the way the Home Assistant UI works, I'm going to be removing the date formatting options as they are now ignored anyway - the UI now recognizes that it is a date and then automatically converts this to a date in the timezone of the browser (it's causing headaches!!).  So it's likely that all date attributes will be returned as a timedate object, which would allow more customization etc via templates etc

**Comment by pinkywafer** [comment]
closed by #120
