### ISSUE TITLE
Make date templateable

### ISSUE THREAD

**Issue by CaptainSweatpants** [pinkywafer/Anniversaries#69]
I have a sensor based off a input_datetime that changes date/time every 10 days. I wanted to use this to show the days remaining from that sensor value.  This possible; or is the only acceptable date format “YYYY-MM-DD”?

**Comment by pinkywafer** [comment]
As things stand, this is not currently possible. The date used is only populated at startup.

But... I'm going to leave this suggestion here, as it would be nice to make the configuration options templateable rather than static, this would mean that you could use a template based on another sensor to set the date

**Comment by pinkywafer** [comment]
Well, there's a downside:
Templates are rendered at run-time, so any errors in the template etc would be logged at run time, not at setup
A further downside is that any string is renderable as a template, which would mean that an invalid date string would be rendered as a template instead, so again, no errors would be given at setup time.
As a way round this, I'm tempted to make a new `date_template` configuration option, and as this is a more advanced feature, I'm tempted to limit it's use to yaml configuration only (the premise being that it's only likely to be something wanted by 'advanced' users)
